<a href="https://colab.research.google.com/github/euguroglu/cave/blob/master/Numpy_trainings2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
data_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(data_list)

In [4]:
arr

array([1, 2, 3])

In [ ]:
data_list2 = ([10,20,30],[40,50,60],[70,80,90])

In [ ]:
arr2 = np.array(data_list2)

In [ ]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr3=np.array([1,2,3,4,5])

In [ ]:
arr3

array([1, 2, 3, 4, 5])

In [ ]:
arr3[0]

1

In [ ]:
arr2[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [ ]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr2[2,2]

90

In [ ]:
arr2[2,2]=24

In [ ]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 24]])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.randint(0,10)

8

In [ ]:
np.random.randint(15)

9

In [ ]:
np.random.randint(1,10,5)

array([2, 9, 1, 4, 9])

In [ ]:
np.random.rand(5)

array([0.0804948 , 0.84704284, 0.33415214, 0.09709338, 0.63544778])

In [ ]:
np.random.randn(5)

array([-1.64095938, -0.32567327, -1.71735631, -1.32807866,  0.36821039])

In [ ]:
arr= np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
newArray = np.random.randint(1,100,10)

In [ ]:
newArray

array([34, 21, 18, 70, 86, 73, 86, 21,  8,  6])

In [ ]:
newArray.max()

86

In [ ]:
newArray.min()

6

In [ ]:
newArray.sum()

423

In [ ]:
newArray.mean()

42.3

In [ ]:
newArray.argmax()

4

In [ ]:
newArray.argmin()

9

In [ ]:
detArray = np.random.randint(1,100,25)

In [ ]:
detArray = detArray.reshape(5,5)

In [ ]:
detArray

array([[ 8, 10, 49, 79, 39],
       [71, 27, 62,  7, 22],
       [82, 73, 13, 50, 73],
       [84, 47, 86, 98, 18],
       [81, 43, 96, 87, 96]])

In [ ]:
np.linalg.det(detArray)

202770115.99999943

In [ ]:
detarray2= np.array([[1,2],[3,5]])

In [ ]:
detarray2

array([[1, 2],
       [3, 5]])

In [ ]:
np.linalg.det(detarray2)

-1.0000000000000004

In [ ]:
round(np.linalg.det(detarray2))

-1.0

In [ ]:
arr = np.arange(1,10)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1]

2

In [ ]:
arr[3]

4

In [ ]:
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
arr[:4]

array([1, 2, 3, 4])

In [ ]:
arr[::2]

array([1, 3, 5, 7, 9])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[:3]

array([1, 2, 3])

In [ ]:
arr[:3]=25

In [ ]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [ ]:
arr = np.arange(1,10)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2= arr

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2[:3]=100

In [ ]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
arr = np.arange(1,10)

In [ ]:
arr2= arr.copy()

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2[:3]=20

In [ ]:
arr2

array([20, 20, 20,  4,  5,  6,  7,  8,  9])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
newarray = np.arange(1,21)

In [ ]:
newarray = newarray.reshape(5,4)

In [ ]:
newarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
newarray[0,0]

1

In [ ]:
newarray[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [ ]:
newarray[:2,:2]

array([[1, 2],
       [5, 6]])

In [ ]:
newarray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
newarray[:2,]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
boolenArray = arr>3

In [ ]:
arr[boolenArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr<4]

array([1, 2, 3])

In [ ]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [ ]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [ ]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [ ]:
arr1 * arr2

array([ 20,  60, 120, 200, 300, 420])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr1 + 10

array([20, 30, 40, 50, 60, 70])

In [ ]:
arr2

array([2, 3, 4, 5, 6, 7])

In [ ]:
arr2 -2

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])