<a href="https://colab.research.google.com/github/euguroglu/cave/blob/master/Numpy_trainings_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.arange(9)
np.mean(a)

4.0

In [4]:
np.std(a)

2.581988897471611

In [6]:
np.argmax(a) #giving index of the maximum value

8

## Linear Algebra

In [8]:
a = 2* np.ones(5)
a

array([2., 2., 2., 2., 2.])

In [10]:
b = np.array([1,2,3,4,5])

In [12]:
a.dot(b)

30.0

In [14]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
a.T #TRANSPOSE

array([[1, 3],
       [2, 4]])

In [17]:
np.linalg.det(a) #determinant

-2.0000000000000004

In [19]:
b = np.linalg.inv(a) #inverse matrix
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
a.dot(b) #identity matrix

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])