In [2]:
data_list=[1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2 = ([10,20,30],[40,50,60],[70,80,90])

In [7]:
arr2 = np.array(data_list2)

In [8]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
arr3=np.array([1,2,3,4,5])

In [10]:
arr3

array([1, 2, 3, 4, 5])

In [11]:
arr3[0]

1

In [12]:
arr2[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr2[2,2]

90

In [15]:
arr2[2,2]=24

In [16]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 24]])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.random.randint(0,10)

8

In [29]:
np.random.randint(15)

9

In [30]:
np.random.randint(1,10,5)

array([2, 9, 1, 4, 9])

In [31]:
np.random.rand(5)

array([0.0804948 , 0.84704284, 0.33415214, 0.09709338, 0.63544778])

In [32]:
np.random.randn(5)

array([-1.64095938, -0.32567327, -1.71735631, -1.32807866,  0.36821039])

In [33]:
arr= np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
newArray = np.random.randint(1,100,10)

In [37]:
newArray

array([34, 21, 18, 70, 86, 73, 86, 21,  8,  6])

In [38]:
newArray.max()

86

In [39]:
newArray.min()

6

In [40]:
newArray.sum()

423

In [41]:
newArray.mean()

42.3

In [42]:
newArray.argmax()

4

In [43]:
newArray.argmin()

9

In [44]:
detArray = np.random.randint(1,100,25)

In [45]:
detArray = detArray.reshape(5,5)

In [46]:
detArray

array([[ 8, 10, 49, 79, 39],
       [71, 27, 62,  7, 22],
       [82, 73, 13, 50, 73],
       [84, 47, 86, 98, 18],
       [81, 43, 96, 87, 96]])

In [47]:
np.linalg.det(detArray)

202770115.99999943

In [50]:
detarray2= np.array([[1,2],[3,5]])

In [51]:
detarray2

array([[1, 2],
       [3, 5]])

In [52]:
np.linalg.det(detarray2)

-1.0000000000000004

In [53]:
round(np.linalg.det(detarray2))

-1.0

In [54]:
arr = np.arange(1,10)

In [55]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[1]

2

In [57]:
arr[3]

4

In [58]:
arr[1:5]

array([2, 3, 4, 5])

In [59]:
arr[:4]

array([1, 2, 3, 4])

In [60]:
arr[::2]

array([1, 3, 5, 7, 9])

In [61]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[:3]

array([1, 2, 3])

In [63]:
arr[:3]=25

In [64]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [65]:
arr = np.arange(1,10)

In [66]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr2= arr

In [68]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr2[:3]=100

In [70]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [71]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [72]:
arr = np.arange(1,10)

In [73]:
arr2= arr.copy()

In [74]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr2[:3]=20

In [76]:
arr2

array([20, 20, 20,  4,  5,  6,  7,  8,  9])

In [77]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
newarray = np.arange(1,21)

In [79]:
newarray = newarray.reshape(5,4)

In [80]:
newarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [81]:
newarray[0,0]

1

In [82]:
newarray[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [83]:
newarray[:2,:2]

array([[1, 2],
       [5, 6]])

In [84]:
newarray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
newarray[:2,]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [89]:
boolenArray = arr>3

In [90]:
arr[boolenArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [91]:
arr[arr<4]

array([1, 2, 3])

In [94]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [95]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [96]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [97]:
arr1 * arr2

array([ 20,  60, 120, 200, 300, 420])

In [98]:
arr1

array([10, 20, 30, 40, 50, 60])

In [99]:
arr1 + 10

array([20, 30, 40, 50, 60, 70])

In [100]:
arr2

array([2, 3, 4, 5, 6, 7])

In [101]:
arr2 -2

array([0, 1, 2, 3, 4, 5])

In [102]:
arr1

array([10, 20, 30, 40, 50, 60])

In [103]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [104]:
arr1

array([10, 20, 30, 40, 50, 60])

In [105]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])