<a href="https://colab.research.google.com/github/euguroglu/cave/blob/master/Numpy_training_'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Training

In [2]:
import numpy as np

Creating Numpy Arrays

In [ ]:
a = np.zeros(5)

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
a=np.ones(5)

In [ ]:
np.random.random(5)

array([0.11308685, 0.23737349, 0.64553041, 0.78771565, 0.98839751])

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.random.random([2,2,])

array([[0.85141292, 0.22586817],
       [0.38605326, 0.01019356]])

In [ ]:
np.array([[1,2],[4,5]])

array([[1, 2],
       [4, 5]])

In [ ]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
a + 5

array([6., 6., 6., 6., 6.])

In [ ]:
a*5

array([5., 5., 5., 5., 5.])

In [ ]:
b = np.arange(1,6)
b

array([1, 2, 3, 4, 5])

In [ ]:
a+b

array([2., 3., 4., 5., 6.])

In [ ]:
b[2:4]

array([3, 4])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [4]:
A = np.array([[2,1],[3,1]])
A

array([[2, 1],
       [3, 1]])

In [6]:
Ainv = np.linalg.inv(A)
Ainv

array([[-1.,  1.],
       [ 3., -2.]])

In [7]:
Ainv.dot(A)

array([[1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 1.0000000e+00]])