<a href="https://colab.research.google.com/github/euguroglu/cave/blob/master/One_hot_encoding_sklearn_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [20]:
List = ['Micheal','Tony','Sara',]

In [21]:
List = np.array(List)

In [22]:
one_hot_enc = OneHotEncoder(sparse=False, categories='auto')
List = List.reshape(-1, 1)
one_hot = one_hot_enc.fit_transform(List)
print(one_hot)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
