<a href="https://colab.research.google.com/github/euguroglu/cave/blob/master/One_Hot_Encoding_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([1, 0, 3])

In [4]:
a

array([1, 0, 3])

In [5]:
b = np.zeros((a.size, a.max()+1))

In [6]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b[np.arange(a.size),a] = 1

In [8]:
b

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])